name: Ergonaut  # Replace with your desired app name

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ">=2.4.4"
  flutter_svg: ">=2.0.10"
  provider: ">=6.1.2"
  shared_preferences: ">=2.2.2"
  win32: ^5.3.0
  win32_registry: ^1.1.2
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
